
/* ================= English layer: Turkish → English phrase dictionary applied to rendered text ================= */
const EN={
/* chrome */
'Nabız Çemberi':'Pulse Circle','Nabız':'Pulse','Çemberi':'Circle','Idle rhythm defense':'Idle rhythm defense','Nasıl oynanır?':'How to play?',
'Sessizlik A.Ş. şehri susturmaya geliyor. Tek savunma senin döngün: her vuruş hem nota kazandırır hem de sahneye yaklaşan susturuculara ateş eder. 42 enstrüman, roller, dalgalar, patronlar, albümler ve altı tema.':'Silence Inc. is coming to mute the city. Your loop is the only defense: every hit earns notes and fires at the silencers approaching the stage. 42 instruments, roles, waves, bosses, albums and six themes.',
'Nota':'Notes','Nota / sn':'Notes / s','Çarpan':'Multiplier','Dalga':'Wave','Hayran':'Fans',
'Başlat':'Play','Durdur':'Stop','Ritme vur':'Tap beat','Ses açık':'Sound on','Ses kapalı':'Sound off','Örnek şarkıyı dinle':'Hear the demo song','Kendi oyununa dön':'Back to your game',
'Ayarlar':'Settings','Örnek şarkılar':'Demo songs','Örnek şarkı · çık':'Demo song · exit','Bölümler':'Sections','Hazır kurulmuş bir şarkıyı dinle. Kendi kaydın bozulmaz; çıkınca kaldığın yerden devam edersin.':'Listen to a ready-made song. Your own save stays untouched; when you leave, you continue where you were.','Öğretici kapatıldı · Ayarlar’dan yeniden başlatabilirsin':'Tutorial closed · restart it from Settings','Kayıt kodu kopyalandı · başka cihazda Ayarlar → Kayıt → yapıştır → Koddan yükle':'Save code copied · on the other device: Settings → Save → paste → Load from code',
'Sahne':'Stage','Stüdyo':'Studio','Koleksiyon':'Collection','Savunma':'Defense','Kitap':'Book','Görünüm':'Look','Albüm':'Album','yeni':'new',
'Hücreye dokun: vuruş ekle. Boş yere dokun ya da boşluk tuşuna bas: ritme vur.':'Tap a cell: add a hit. Tap an empty spot or press space: tap the beat.',
'Satırdaki hücreye dokun: vuruş ekle. Sahne alanına dokun ya da boşluk tuşuna bas: ritme vur.':'Tap a cell in a row: add a hit. Tap the stage field or press space: tap the beat.',
'Dolgu: vurmalı halkalarının sağ yarısına vuruş koy; sol yarı ve melodikler dolguda çalmaz.':'Fill: place hits on the right half of the percussion rings; the left half and melodic rings do not play in the fill.',
/* studio */
'Her sahne yerinde bir enstrüman durur; desen yere aittir, seviye enstrümana. Her enstrümanın ölçü başına bir':'Each stage slot holds one instrument; the pattern belongs to the slot, the level to the instrument. Every instrument has one',
'nefesi':'breath','vardır: o kadar vuruşa kadar tam güç, fazlası her vuruşu zayıflatır; aksan iki nefes harcar. Düşmanlar art arda gelen aynı sese':'per bar: full power up to that many hits, more weakens every hit; an accent costs two breaths. Enemies get used to the same sound in a row',
'alışır':'habituate',': her ardışık vuruşta hasar ×0,85, bir es sıfırlar.':': each consecutive hit ×0.85 damage, one rest resets it.',
'Desen A’yı temizle':'Clear pattern A','Desen B’yi temizle':'Clear pattern B','Solo desenini temizle':'Clear the solo pattern','Dolgu’yu temizle':'Clear the fill','İkisini de temizle':'Clear both','Sahne yeri ekle':'Add stage slot','Sahne dolu: 10 yer':'Stage full: 10 slots',
'Desen, ölçü ve gam':'Pattern, meter and scale','Düzenlenen':'Editing','Desen A':'Pattern A','Desen B':'Pattern B','Solo deseni':'Solo pattern','Dolgu':'Fill','B deseni ilk albümle açılır':'Pattern B opens with the first album','Kopyala':'Copy','A’yı B’ye kopyala':'Copy A to B','Ölçü':'Meter','Gam':'Scale',
'Şarkı planı':'Song plan','Solo editörü':'Solo editor','Solo dalı':'Solo branch','Ritim stüdyosu':'Rhythm studio','Uyum':'Harmony','Groove':'Groove',
'Enstrümanlar arası ilişkiler. Tutan her uyum, içindeki halkaların notasını ve hasarını çarpar. Kurallar gerçek groove mantığından alındı: bas kick ile kilitlenir, alkış trampetin üstüne biner, hi-hat araları doldurur, melodiler birbirine cevap verir.':'Relationships between instruments. Every harmony that holds multiplies the notes and damage of its rings. The rules come from real groove logic: bass locks to the kick, clap layers on the snare, hi-hat fills the gaps, melodies answer each other.',
'Bonuslar toplanır ve hem notayı hem hasarı çarpar. Bir adıma 6+ vuruş yığmak cezalıdır.':'Bonuses add up and multiply both notes and damage. Piling 6+ hits on one step is penalized.',
'Tempo':'Tempo','teması':'theme','sever':'likes','uyum ×1,25 aktif':'fit ×1.25 active','ücretsiz':'free','Maksimum':'Maximum','Tempoyu 10 BPM düşür':'Lower tempo by 10 BPM',
'Alındı':'Owned','Aç · ♪':'Unlock · ♪','kilitli':'locked','Sahnede':'On stage','Yedekte':'On the bench','Sahneye koy':'Put on stage','Aç':'Unlock','vuruş':'hits','hasar':'damage','nefes':'breath','tam güç':'full power','fazla, güç ×':'too many, power ×','seviyede ×2':'level: ×2','uyum ×':'harmony ×','SUSTURULDU':'MUTED',
'Yer':'Slot','boş':'empty','koleksiyondan enstrüman aç':'unlock an instrument in the Collection','yedekten seç':'pick from the bench','Bu sahne yeri boş. Stüdyo sekmesinden bir enstrüman koy.':'This stage slot is empty. Put an instrument in from the Studio tab.',
'döngüde normal çalar, solo bölümünde solo desenini ×3 çalar':'plays normally in the loop, plays its solo pattern ×3 in the solo section','Yeri temizle':'Clear slot','Bu yerin vuruşlarını kaldır':'Remove this slot’s hits','İbre':'Needle','Sahne yeri':'Stage slot',
'Öklid üretici':'Euclid generator','Uygula':'Apply','geri':'back','Yeterli nota yok':'Not enough notes','gerekli':'needed','Aksan için':'For an accent',
/* collection */
'Her enstrümanın bir nota değeri ve bir rolü vardır. Silah rolleri ateş eder; Titreşim ses duvarını iter, Destek aynı adımdaki silahları güçlendirir, Gelir yalnız nota kazandırır, Kalkan sahneyi korur.':'Every instrument has a note value and a role. Weapon roles fire; Vibration pushes the sound wall, Support boosts weapons on the same step, Income only earns notes, Shield protects the stage.',
'Sıradaki aile':'Next family','ailesi':'family','enstrüman':'instruments','Aileyi aç':'Open the family','kapı':'gate','Bütün aileler açık. 42 enstrümanın hepsi koleksiyonda.':'All families open. All 42 instruments are in the collection.','açık':'open','ateş etmez':'does not fire','albüm':'albums','ödeme':'payment','En iyi dalga':'Best wave','hayran':'fans',
'Vurmalı':'Percussion','Tel':'Strings','Tuş':'Keys','Nefesli':'Winds','Elektronik':'Electronic','Dünya':'World',
/* roles */
'Darbe':'Strike','Keskin':'Sharp','Seri':'Rapid','Alan':'Area','Delici':'Piercer','Yavaşlatıcı':'Slower','Güdümlü':'Homing','Kalkan':'Shield','Zincir':'Chain','Statik':'Static','Sarsıcı':'Stunner','Kritik':'Critical','Titreşim':'Vibration','Gelir':'Income','Destek':'Support',
'En yakına ağır vuruş, yanındakilere sıçrar':'Heavy hit on the nearest, splashes to neighbors','En sağlam düşmanı hedefler, %20 kritik':'Targets the toughest enemy, 20% crit','Rastgele düşmana hafif vuruş, zırha yarı işler':'Light hit on a random enemy, half effect on armor','Menzildeki herkese vurur':'Hits everyone in range','Aynı hattaki tüm düşmanları deler':'Pierces every enemy in the same lane','Vurur ve yavaşlatır':'Hits and slows','En hızlı düşmanı bulur':'Finds the fastest enemy','Sahneye kalkan ekler, hasar vermez':'Adds shield to the stage, no damage','Bir düşmandan iki düşmana daha sıçrar':'Jumps from one enemy to two more','Zamanla hasar, hafif yavaşlatma':'Damage over time, light slow','Vurur ve kısa süre durdurur':'Hits and stops briefly','%35 ihtimalle üç kat vurur':'35% chance to hit triple','Ateş etmez; ses duvarını dışarı iter, çubuğa değen düşman hasar alır':'Does not fire; pushes the sound wall outward, enemies touching the bars take damage','Ateş etmez; vuruş başı nota ×3':'Does not fire; ×3 notes per hit','Ateş etmez; aynı adımda vuran her silah ×1,5':'Does not fire; every weapon hitting on the same step ×1.5',
/* instruments */
'Davul':'Kick drum','Trampet':'Snare','El çırpma':'Clap','Kaşık':'Spoons','Zil':'Crash','Timbal':'Timpani','Bas':'Bass','Akustik gitar':'Acoustic guitar','Gitar':'Guitar','Keman':'Violin','Çello':'Cello','Arp':'Harp','Akor':'Chord pad','Piyano':'Piano','Org':'Organ','Klavsen':'Harpsichord','Flüt':'Flute','Trompet':'Trumpet','Saksafon':'Saxophone','Gürültü':'Noise','Arpej':'Arpeggio',
'Döngünün temeli':'Foundation of the loop','Arka vuruş':'Backbeat','Kuru tıkırtı, aynı adımdaki silahları güçlendirir':'Dry rattle, boosts weapons on the same step','Aralardaki tıs, aksanlı açık':'Hiss in the gaps, open on accents','Trampete katman: aynı adımdaki silahları güçlendirir':'Layer on the snare: boosts weapons on the same step','Tahta şakırtı, sert kritik':'Wooden clatter, hard crit','Dolgu davulu':'Fill drum','Adıma göre düm ya da tek':'Dum or tek by step','Derin çerçeve davul, sarsar':'Deep frame drum, stuns','Crash: sahnedeki herkese':'Crash: everyone on stage','Akortlu orkestra davulu, ses duvarını iter':'Tuned orchestral drum, pushes the sound wall','Bir vuruş, uzun titreşim; duvarı en çok iten':'One hit, long vibration; pushes the wall the most','Akor yürüyüşünü izler, hattı deler':'Follows the chord progression, pierces the lane','Tel çınlaması, akor tarar; nota kazandırır':'String ring, strums chords; earns notes','Distorsiyonlu güç akoru':'Distorted power chord','Bağlama tınısı, düşmandan düşmana sıçrar':'Bağlama tone, jumps from enemy to enemy','Yay ve vibrato, en hızlıyı bulur':'Bow and vibrato, finds the fastest','Kalın yay, hattı deler':'Thick bow, pierces the lane','Her glisando nota, ateş etmez':'Every glissando earns notes, does not fire','Synth pad, yavaşlatır':'Synth pad, slows','Sıcak elektrikli piyano, nota kazandırır':'Warm electric piano, earns notes','Sert tuşe, en sağlamı hedefler':'Hard touch, targets the toughest','Çekilen registerler, kalkan':'Drawn registers, shield','Barok çıtırtı, kritik':'Baroque crackle, crit','Nefesli, hüzünlü, güdümlü':'Breathy, melancholic, homing','Tiz ve çevik':'High and agile','Parlak patlama':'Bright blast','Hırıltılı, sıçrar':'Growly, jumps','Ağır bakır, ses duvarını iter':'Heavy brass, pushes the sound wall','Düğün sesi, herkese':'Wedding sound, hits everyone','Synth lead, en hızlıyı bulur':'Synth lead, finds the fastest','Uzun sub bas, ses duvarını iter':'Long sub bass, pushes the sound wall','Arpejiyatör, sıçrar':'Arpeggiator, jumps','Dokunmadan çalınır, statik bırakır':'Played without touching, leaves static','Beyaz gürültü yükselişi':'White-noise riser','Robot koro, aynı adımdaki silahları güçlendirir':'Robot choir, boosts weapons on the same step','Başparmak piyanosu, nota kazandırır':'Thumb piano, earns notes','Karayip çeliği, nota kazandırır':'Caribbean steel, earns notes','Na ve ge, kritik':'Na and ge, crit','Dairesel nefes, duvarı sürekli iter':'Circular breathing, pushes the wall constantly','Devasa davul, duvarı fırlatır':'Giant drum, hurls the wall','Bronz metalofon, herkese':'Bronze metallophone, hits everyone',
/* rhythm studio */
'Swing':'Swing','Aksan':'Accent','Eko pedalı':'Echo pedal','Metronom asistanı':'Metronome assistant','Sidechain pompası':'Sidechain pump','Filtre süpürmesi':'Filter sweep','Akor yürüyüşü':'Chord progression','Solo izni':'Solo permit','İkinci ibre':'Second needle','Üçüncü ibre':'Third needle','Şef':'Conductor',
'Ara vuruşlar geriden gelir · gelir ×1,15':'Off-beats come late · income ×1.15','Dolu hücreye ikinci dokunuş: nota ve hasar iki katı':'Second tap on a filled cell: double notes and damage','Vuruşları bir sahne yerine eşit aralıkla dağıtır':'Spreads hits evenly across one stage slot','Tel, tuş ve nefeslilere yankı · ×1,15':'Echo on strings, keys and winds · ×1.15','Sen bakmazken de seri en az 6 kalır':'Streak stays at least 6 while you are away','Her davulda müzik nefes alır · ×1,15':'The music breathes on every kick · ×1.15','Her dördüncü ölçünün sonu vurgulu · hasar ×1,1':'End of every fourth bar accented · damage ×1.1','Ses yavaşça açılıp kapanır · ×1,15':'Sound opens and closes slowly · ×1.15',
'Şarkı planında her bölüme akor yürüyüşü ve akor hızı seçilir. Akor izleyen enstrümanlar ona uyar; zıtlık, kadans ve makam sadakati bonus verir':'Pick a chord progression and chord rate per section in the song plan. Chord-following instruments obey it; contrast, cadence and makam fidelity give bonuses',
'Desen anahtarına Dolgu eklenir: her bölümün son ölçüsünün son yarısında vurmalılar dolgu desenini çalar, oyun zil ile çözer; geçiş düşmanı sarsar ve sonraki ölçüyü güçlendirir':'Adds Fill to the pattern switch: in the last half of each section’s last bar the percussion plays the fill pattern, the game resolves it with a crash; the transition stuns enemies and boosts the next bar',
'Sahne yerlerini soloya ayırabilirsin: solo yeri döngüde normal çalar, solo bölümünde kendi solo desenini ×3 güçle çalar. Solo dalının ilk düğümü.':'You can assign stage slots to solo: a solo slot plays normally in the loop and plays its own solo pattern at ×3 power in the solo section. First node of the solo branch.',
'Seçtiğin yerleri ¾ hızda ayrı bir ibre çalar: 4’e karşı 3, dört ölçüde bir buluşurlar':'A separate needle plays chosen slots at ¾ speed: 3 against 4, they meet once every four bars','Seçtiğin yerleri yarı hızda ve ters yönde çalan üçüncü ibre: desen geriye doğru okunur':'A third needle plays chosen slots at half speed and backwards: the pattern reads in reverse','Şarkı planı: 8 bölüm × 4 ölçü. Giriş, kıta, nakarat, köprü, yükseliş, düşüş, solo, çıkış; sen dizersin':'Song plan: 8 sections × 4 bars. Intro, verse, chorus, bridge, build, drop, solo, outro; you arrange them',
/* sections */
'Giriş':'Intro','Kıta':'Verse','Nakarat':'Chorus','Köprü':'Bridge','Yükseliş':'Build','Düşüş':'Drop','Çıkış':'Outro',
'Yalnız ritim grubu; nabız 4 kat hızlı yenilenir':'Rhythm section only; pulse regenerates 4× faster','Herkes çalar, desen A':'Everyone plays, pattern A','Herkes çalar, desen B, güç ×1,2':'Everyone plays, pattern B, power ×1.2','Yalnız melodikler; düşmanlar %20 yavaş':'Melodic only; enemies 20% slower','Tempo 4 ölçüde %15 hızlanır, güç yükselir':'Tempo rises 15% over 4 bars, power climbs','Tempo yerine oturur, desen B, güç ×1,3':'Tempo settles, pattern B, power ×1.3','Solo yerleri sırayla çalar (güç ×3)':'Solo slots play in turn (power ×3)',
'Şarkı 8 bölüm × 4 ölçü = 32 ölçü döner. Bölümleri sen dizersin; 4+ farklı bölüm türü':'The song loops 8 sections × 4 bars = 32 bars. You arrange the sections; 4+ different section types','şarkı bonusu ×1,25':'song bonus ×1.25','verir.':'.','bölüm':'section','Pop':'Pop','Kulüp':'Club','Solo gecesi':'Solo night','Döngü':'Loop',
'Akor hızı':'Chord rate','Vuruş başına (dört akor her ölçüde)':'Per beat (four chords in every bar)','Ölçü başına (bölümün dört ölçüsünde dört akor)':'Per bar (four chords over the section’s four bars)','zıtlık':'contrast','yok':'none','kadans':'cadence','makam':'makam',
'Kadans: bölüm V ile bitip sonraki kökle başlarsa geçiş ölçüsü ×1,25. Zıtlık: iki farklı yürüyüş ×1,1. Hicaz/kürdide Durak–Güçlü ×1,1.':'Cadence: if a section ends on V and the next starts on the root, the transition bar is ×1.25. Contrast: two different progressions ×1.1. Durak–Güçlü in hicaz/kürdi ×1.1.',
'Tek kök':'Single root','Durak (dem)':'Tonic (drone)','Durak–Güçlü':'Tonic–Dominant',
/* fills */
'Tek vuruş':'Single hit','Sekizlik yükseliş':'Eighth-note build','On altılık koşu':'Sixteenth run','Üçleme':'Triplet','Dolgu üret':'Generate fill','Sahnedeki vurmalılara dağıt':'Spread over stage percussion','dolgu vuruşu':'fill hits',
'Dolgu: her bölümün son ölçüsünün sağ yarısında vurmalılar bu deseni çalar, melodikler normal devam eder. Nefes kuralı işlemez ama her vuruş %60 değerinde, satır başına en çok 8 vuruş. 4+ vuruşluk dolgu zille çözülür: düşman 0,4 sn sarsılır, sonraki ölçü ×1,25 (kadansla ×1,5).':'Fill: in the right half of each section’s last bar the percussion plays this pattern, melodic rings carry on. The breath rule does not apply but each hit is worth 60%, at most 8 hits per row. A fill of 4+ hits resolves with a crash: enemies stunned 0.4 s, next bar ×1.25 (×1.5 with a cadence).',
'Dolgu yalnız vurmalı satırlarda çalınır':'Fills only play on percussion rows','Dolgu ölçünün son yarısında çalar: vuruşu sağ yarıya koy':'The fill plays in the last half of the bar: place the hit on the right half','Satır başına en çok 8 dolgu vuruşu':'At most 8 fill hits per row',
/* solo */
'Düz':'Plain','Sahne devri':'Stage takeover','Uzun nota':'Long note','İkinci oktav':'Second octave','Doruk':'Peak','Sualli-cevaplı':'Call and response','Seyir':'Seyir (shape)','Bis':'Encore',
'Tel: bend & vibrato':'Strings: bend & vibrato','Tel: tremolo / feedback / slap':'Strings: tremolo / feedback / slap','Nefesli: dairesel nefes':'Winds: circular breathing','Nefesli: growl & bend':'Winds: growl & bend','Tuş: sustain pedalı':'Keys: sustain pedal','Tuş: glissando':'Keys: glissando','Elektronik: portamento':'Electronic: portamento','Elektronik: arpejiyatör':'Electronic: arpeggiator',
'Solo bölümünde sahne solistin olur: halkalar notaya dönüşür (içerisi pes, dışarısı tiz), ibre yarı hıza düşer, solo doğrudan sahnede çizilir.':'In the solo section the stage belongs to the soloist: rings become pitches (inner low, outer high), the needle slows to half, the solo is drawn right on the stage.',
'Notayı halka boyunca sürükleyerek uzat. Gücün nasıl düştüğünü enstrümanın türü belirler: sönen tel, tutan ses, nefesli.':'Extend a note by dragging it along the ring. The instrument type decides how power fades: decaying string, sustaining voice, wind.',
'Halka sayısı iki katına çıkar: tiz bölge açılır.':'Ring count doubles: the high register opens.','Tepe bölgede 4+ adım tutulan nota sahneyi dolduran bir patlama yapar: herkese hasar, +1 hayran.':'A note held 4+ steps in the top register fills the stage with a burst: damage to everyone.','İki solist 4 adımlık cümlelerle birbirine cevap verir; ikisi de ×1,2 güçle çalar.':'Two soloists answer each other in 4-step phrases; both play at ×1.2.',
'Telli ve yaylı solistlere bend, vibrato ve slide.':'Bend, vibrato and slide for string and bowed soloists.','Saz, akustik, arp: tremolo (uzun nota sönmez, yarı güçte sürer). Elektro: feedback (uzadıkça güçlenir, 16 adımdan sonra ıslık). Bas: slap & pop.':'Saz, acoustic, harp: tremolo (a long note no longer decays, holds at half power). Electric: feedback (grows the longer it lasts, squeals after 16 steps). Bass: slap & pop.','Nefes sınırı kalkar; vibrato açılır.':'The breath limit is removed; vibrato opens.','Hırıltı (growl) ve nefesli bend.':'Growl and wind bend.','Tuşlular pedalla daha yavaş söner (0,78 → 0,90).':'Keys decay slower with the pedal (0.78 → 0.90).','Tuşlulara slide (glissando).':'Slide (glissando) for keys.','Synth ve theremin notalar arasında kayar (slide), vibrato yapar.':'Synth and theremin glide between notes (slide) and vibrate.','Uzun nota yukarı doğru arpej olur: her adım bir üst halka.':'A long note becomes an upward arpeggio: one ring up per step.',
'Solonun biçimi puanlanır: Karar (kökte uzun bitiş ×1,25), Doruk (tepede 4+ adım ×1,2), Soru–cevap (cümle arası nefes ×1,15).':'The solo’s shape is scored: Cadence (long ending on the root ×1.25), Peak (4+ steps at the top ×1.2), Call–response (a breath between phrases ×1.15).','Solo bölümü iki kat sık gelir: her 12 ölçüde 4 ölçü.':'The solo section comes twice as often: 4 bars in every 12.',
'Sahnede düzenle':'Edit on stage','Sahnede düzenleniyor':'Editing on stage','Desen A’ya dön':'Back to pattern A','Solo yeri':'Solo slot','Stil':'Style','Üret':'Generate','Varyasyon':'Variation','Temizle':'Clear','nota':'notes','Nota seçili değil':'No note selected','Uzat':'Extend','Kısalt':'Shorten','Sil':'Delete','Karar ×1,25':'Cadence ×1.25','Doruk ×1,2':'Peak ×1.2','Soru–cevap ×1,15':'Call–response ×1.15','Makineli yok':'No machine-gun','Makineli':'Machine-gun',
'Sönen tel':'Decaying string','Tutan ses':'Sustaining voice','sönme ×':'decay ×','/ adım':'/ step','adımda biter':'steps until silent','sınırsız (dairesel nefes)':'unlimited (circular breathing)','adım, sonra kesilir':'steps, then cuts off','hiç bitmez, güç her adımda yavaş düşer':'never ends, power drops slowly each step','uzun nota için dalda “Uzun nota” gerekir':'“Long note” in the branch is needed for long notes',
'Blues pentatonik, bend ve vibratolu uzun notalar, çift sesler, es payı':'Blues pentatonic, long notes with bend and vibrato, double stops, room to breathe','Hızlı 16’lık koşular, oktav atlamalar, slap ve pop':'Fast 16th runs, octave jumps, slap and pop','Basamak basamak yürüyen uzun notalar, slide ile giriş, geç vibrato, süslemeler':'Long notes stepping up and down, slide entries, late vibrato, ornaments','Arpej koşuları ve tutulan tepe notası':'Arpeggio runs and a held top note',
'Sahne: solo nereye kadar büyür':'Stage: how far the solo grows','Teknikler: aileye özel, her biri ayrı alınır':'Techniques: per family, each bought separately','Biçim: iyi kurulmuş solo ödüllenir':'Form: a well-built solo is rewarded','önce':'first',
/* defense */
'Kuşatma':'Siege','Savunma geliştirmeleri':'Defense upgrades','Siparişler':'Orders','Sessizlik A.Ş. kadrosu':'Silence Inc. roster','Şehirden gelen müzik istekleri. Koşulları sağlayıp teslim et; ödül şu anki gelirine göre hesaplanır.':'Music requests from the city. Meet the conditions and deliver; the reward scales with your current income.',
'Hasar':'Damage','Menzil':'Range','Kalkan kapasitesi':'Shield capacity','Tamir':'Repair','Ganimet':'Bounty','Yavaşlatma gücü':'Slow power','Sahne dayanıklılığı +60':'Stage durability +60','Tüm vuruşlar +%12':'All hits +12%','Düşmanlar daha uzaktan hedeflenir':'Enemies targeted from farther','Kalkan üst sınırı +50':'Shield cap +50','Saniyede +1 nabız yenilenir':'+1 pulse regenerated per second','Düşman ödülü +%25':'Enemy bounty +25%','Yavaşlatıcı etkisi +%10':'Slow effect +10%',
'Memur':'Clerk','Kurye':'Courier','Stajyer':'Intern','Avukat':'Lawyer','Sansürcü':'Censor','Denetçi':'Auditor','Müdür':'Manager','Yürür, dosya taşır':'Walks, carries files','Hızlı, kırılgan':'Fast, fragile','Sürü halinde, bedava çalışır':'Comes in swarms, works for free','Zırhlı; Seri yarı işler':'Armored; Rapid hits at half','Sahneye ulaşırsa bir enstrümanı bir ölçü susturur':'Mutes an instrument for a bar if it reaches the stage','Her 10. dalga; yavaşlamaz':'Every 10th wave; cannot be slowed','Her 25. dalga; stajyer çağırır':'Every 25th wave; calls interns','Her 50. dalga; kurye çağırır, yavaşlamaz':'Every 50th wave; calls couriers, cannot be slowed',
'dalga geri':'waves back','ileri':'forward','DALGA · EN İYİ':'WAVE · BEST','SAHNEDEKİ DÜŞMAN':'ENEMIES ON STAGE','HASAR / SN':'DAMAGE / S','SUSTURULAN':'SILENCED','Bu dalga':'This wave','memur':'clerks',
/* look */
'Düzen':'Layout','Temalar':'Themes','Sahne katmanları':'Stage layers','Efekt laboratuvarı':'Effects lab','Çember':'Circle','Şerit':'Strip',
'Çember: halkalar ve dönen ibre, düşmanlar her yönden gelir. Şerit: satırlar ve kayan çubuk, önünde ekolayzer silüeti, düşmanlar yukarıdan iner.':'Circle: rings and a rotating needle, enemies come from every direction. Strip: rows and a sliding bar with an equalizer silhouette, enemies descend from above.',
'Tema görüntüyü, ses rengini ve düşman çizimini değiştirir. Temanın sevdiği tempoda çalarsan gelir ×1,25.':'A theme changes the look, the sound color and the enemy drawing. Play at the theme’s favorite tempo for ×1.25 income.',
'Albümden sonra da kalır, her biri gelire ×1,1 ekler ve her düzende farklı çizilir.':'Kept after albums, each adds ×1.1 income and is drawn differently in each layout.','Kullanılıyor':'In use','sn önizle':'s preview','Sevdiği tempo':'Favorite tempo',
'Örnek sesler':'Sampled sounds','Teller, tuşlular, nefesliler ve davul seti gerçek enstrüman kayıtlarıyla (FluidR3 General MIDI, MIT lisanslı) çalar; saz, elektronik aile, didgeridoo ve tabla sentez kalır. Kayıt yüklenemezse sentez devam eder.':'Strings, keys, winds and the drum kit play real instrument recordings (FluidR3 General MIDI, MIT licensed); saz, the electronic family, didgeridoo and tabla stay synthesized. If a recording cannot load, synthesis carries on.','Örnek ses seviyesi':'Sample level','Kayıtların sentez katmanına göre yüksekliği':'Loudness of the recordings relative to the synth layer','yüklenemedi, sentez kullanılıyor':'failed to load, using synthesis','Açık':'On','Kapalı':'Off','Örnek sesler kapalı: sentez':'Samples off: synthesis','Sahnede örneklenmiş enstrüman yok':'No sampled instrument on stage','Örnek sesler:':'Samples:','yüklendi':'loaded','yüklenemedi (bu ortamda engelli, sentez kullanılıyor)':'failed (blocked here, using synthesis)',
/* album */
'Albüm çıkarınca döngü, sahne, seviyeler, savunma geliştirmeleri ve dalga sıfırlanır. Hayranlar, bulunan kalıplar, açılan aileler, temalar ve sahne katmanları kalır. Her hayran gelire kalıcı %5 ekler.':'Releasing an album resets the loop, stage, levels, defense upgrades and wave. Fans, found patterns, opened families, themes and stage layers stay. Every fan adds a permanent 5% income.',
'Albüm çıkar':'Release album','Menajer':'Manager','Dünya turnesi':'World tour','Kayıt':'Save','Kodu üret ve kopyala':'Generate and copy code','Koddan yükle':'Load from code','Öğreticiyi başlat':'Start tutorial','Test: +10 dk gelir':'Test: +10 min income','Kaydı sıfırla':'Reset save','Turneye çık':'Go on tour','Hazır':'Ready',
'Kayıt bu tarayıcıda durur. Başka cihaza taşımak için kodu üret ve kopyala; orada yapıştırıp yükle. Yükleme buradaki kaydın yerine geçer.':'The save lives in this browser. To move it to another device, generate and copy the code; paste and load it there. Loading replaces the save here.','Kayıt kodu burada görünür; yüklemek için kodu buraya yapıştır':'The save code appears here; paste a code here to load it',
'Menajer: seviye':'Manager: levels','Menajer: sipariş':'Manager: orders','Menajer: sahne':'Manager: stage','Menajer: albüm':'Manager: albums','10 saniyede bir, notanın yarısını aşmayan en ucuz seviyeyi sahnedeki enstrümanlara alır':'Every 10 seconds buys the cheapest level on stage that costs at most half your notes','Koşulu sağlanan siparişi kendisi teslim eder':'Delivers orders whose conditions are met','Boş yer varsa ve notanın dörtte birine sığıyorsa açık ailelerden sıradaki enstrümanı açar, sahneye koyar ve rolüne uygun basit bir desen çizer':'If a slot is empty and it costs at most a quarter of your notes, unlocks the next instrument from open families, places it and draws a simple pattern for its role','Dönem kazancı eşiğin iki katına ulaşınca albümü kendisi çıkarır':'Releases the album once the run has earned twice the threshold',
'Menajer ilk albümle gelir: seviye alma, sipariş teslimi, sahne kurma ve albüm çıkarma kademe kademe otomatikleşir; her kademe ayrı alınır ve istediğin an kapatılır.':'The manager arrives with the first album: levels, order delivery, stage setup and album releases automate tier by tier; each tier is bought separately and can be switched off at any time.','Albümden albüme kalır. Açık olanlar sen yokken de çalışır (çevrimdışı değil, sekme açıkken).':'Kept from album to album. Active tiers work while you are away (with the tab open, not offline).','albümle':'album',
'şehir':'city','turne':'tour','Efsane':'Legend','gelir ve hasar ×':'income and damage ×','gezilen şehir':'cities visited','her biri +%2':'each +2%','Sevdiği gam':'Favorite scale','ölçü':'bar','uyuyor ×1,1':'matches ×1.1',
'Turne: 6 albümden sonra çıkılır. Albümler ve hayranlar sıfırlanır, albüm eşiği başa döner; kalıplar, aileler, temalar, sahne katmanları, menajer ve açılan ölçü/gamlar kalır. Karşılığı kalıcı Efsane: şu an çıkarsan +':'Tour: available after 6 albums. Albums and fans reset and the album threshold starts over; patterns, families, themes, stage layers, the manager and unlocked meters/scales stay. The reward is permanent Legend: leaving now gives +','(2·√hayran + albüm). Sıradaki şehir:':'(2·√fans + albums). Next city:',
'Hicaz ve 9/8 sever; sansürcüler kalabalık':'Likes hicaz and 9/8; censors are plentiful','Minör ve 4/4; kuryeler hızlı ve çok':'Minor and 4/4; couriers fast and many','Majör; kalkanlı avukatlar':'Major; shielded lawyers','Majör; stajyer sürüleri':'Major; intern swarms','Minör ve 7/8; her tür biraz daha fazla':'Minor and 7/8; a bit more of everything','Kürdi ve 5/8; hızlı ve kalabalık':'Kürdi and 5/8; fast and crowded','Sessizlik en güçlü burada: sansürcü iki kat':'Silence is strongest here: censors doubled','Hicaz ve 7/8; memur ordusu':'Hicaz and 7/8; an army of clerks',
'B deseni · Şerit düzeni':'Pattern B · Strip layout','9/8 aksak ölçü':'9/8 aksak meter','Hicaz makamı':'Hicaz makam','7/8 ve 5/8 ölçüleri':'7/8 and 5/8 meters','Kürdi makamı':'Kürdi makam','Dünya turnesi: şehirler ve Efsane':'World tour: cities and Legend',
/* book */
'Dört vuruş':'Four on the floor','Yarım tempo':'Half time','Ofbit':'Offbeat','Sekizlikler':'Eighths','Yedi zaman':'Seven time','Türk aksağı':'Turkish aksak','Kalıp bulundu':'Pattern found','keşif':'discovery','çalınca':'when played',
/* tutorial */
'Öğretici':'Tutorial','Atla':'Skip','İleri':'Next','Anladım':'Got it','Bitir':'Finish','Geç':'Pass','Yapınca kendiliğinden ilerler':'Advances by itself when you do it',
'Hoş geldin':'Welcome','Sessizlik A.Ş. şehri susturmaya geliyor; tek savunma senin döngün. Halkada boş bir hücreye dokun: vuruş ekle.':'Silence Inc. is coming to mute the city; your loop is the only defense. Tap an empty cell on the ring: add a hit.',
'Başlat’a bas. İbre döndükçe her vuruş hem nota kazandırır hem de yaklaşan susturuculara ateş eder.':'Press Play. As the needle turns, every hit earns notes and fires at the approaching silencers.',
'Düşmanlar kenardan merkeze yürür. Merkeze varırlarsa Nabız düşer; sıfırlanırsa dalga 5 geri gider. İlk susturucuyu düşür.':'Enemies walk from the edge to the center. If they reach it, Pulse drops; at zero you fall back 5 waves. Take down the first silencer.',
'Seviye':'Level','Biriken notayla Stüdyo’dan Davul’u yükselt: her seviye değeri artırır, 10. ve 25. seviyede ikiye katlar.':'Spend notes in the Studio to level the kick: every level raises its value, levels 10 and 25 double it.',
'Nefes':'Breath','Her enstrümanın ölçü başına bir nefesi var: Davul 4 vuruşa kadar tam güç, fazlası zayıflar. Her hücreyi doldurmak kazandırmaz; es bırak, yerine aksan koy.':'Every instrument has a breath per bar: the kick is at full power up to 4 hits, more weakens. Filling every cell does not pay; leave rests, add accents instead.',
'Koleksiyon sekmesinden ikinci bir vurmalı aç (trampet ya da alkış). Alkış trampetin üstüne biner, hi-hat araları doldurur: uyumlar çarpan verir. Diğer aileler dalga ilerledikçe açılır.':'Unlock a second percussion instrument in the Collection tab (snare or clap). Clap layers on the snare, hi-hat fills the gaps: harmonies give multipliers. Other families open as waves progress.',
'İkinci halka':'Second ring','Yeni enstrüman 2. yere kondu. Onun halkasına da en az iki vuruş ekle; birbirine cevap veren desenler Uyum kazandırır.':'The new instrument went into slot 2. Add at least two hits to its ring too; patterns that answer each other earn Harmony.',
'İbre bir vuruşun üstündeyken sahnede boş bir yere dokun (ya da boşluk tuşuna bas): seri bonusu. Üç kez üst üste tuttur.':'While the needle is over a hit, tap an empty spot on the stage (or press space): streak bonus. Hit it three times in a row.',
'Savunma sekmesinde Nabız, hasar ve menzil geliştirmeleri var; Siparişler ekstra ödül verir. Dalga ilerledikçe patronlar gelir.':'The Defense tab has Pulse, damage and range upgrades; Orders give extra rewards. Bosses arrive as waves progress.',
'Dönemde yeterince nota kazanınca Albüm çıkar: hayran kazanırsın, döngü sıfırlanır ama hayranlar kalıcı çarpan verir. Kitap kalıpları, temalar ve solo dalı seni bekliyor.':'Earn enough notes in a run and release an Album: you gain fans, the loop resets, but fans give a permanent multiplier. Book patterns, themes and the solo branch await.',
/* messages and canvas */
'Solo:':'Solo:','Solo ·':'Solo ·','SUS':'MUTED','NEFES':'BREATH','GEÇİŞ':'TRANSITION','KARAR':'CADENCE','SORU-CEVAP':'CALL-RESPONSE','MAKİNELİ':'MACHINE-GUN','1. ölçü':'bar 1','2. ölçü':'bar 2','alındı':'bought','teslim edildi':'delivered','açıldı':'unlocked','Menajer dalgayı ileri aldı':'Manager advanced the wave','Örnek şarkı':'Demo song','örnek şarkı':'demo song','çember':'circle','şerit':'strip','önizleme':'preview','Sen yokken döngün':'While you were away your loop earned','kazandırdı · kuşatma seni bekledi':'· the siege waited for you',
'bir barı başka bara değdir: tek bar olurlar':'touch one bar to another: they become one bar','Barlar birleşti':'Bars merged','bara değdir, birleşir':'touch a bar, they merge','Solo sahnesi':'Solo stage','boş yere bas, nota':'tap empty space, note','halka boyunca sürükle, uzat':'drag along the ring, extend','başka halkaya sürükle, perde':'drag to another ring, pitch','merkez: ritme vur':'center: tap the beat','adım':'steps','Diğer örnek şarkı':'Other demo song','Örnek şarkı 1':'Demo song 1','Örnek şarkı 2':'Demo song 2',
/* demo songs */
'Gece Vardiyası':'Night Shift','Boğaz’da Düet':'Duet on the Bosphorus','nasıl kuruldu:':'— how it was built:','Kendi oyununa döndün':'Back in your own game','8 enstrüman, 8 bölüm, solo 4. bölümde':'8 instruments, 8 sections, solo in section 4','hicaz, akor yürüyüşü, dolgu ve gitar–ney düeti · solo 4. ve 8. bölümde':'hicaz, chord progression, fill and a guitar–ney duet · solos in sections 4 and 8',
'Akor ölçü başına: nakarat ve yükseliş kadansla (E) bitip kıtaya çözülür':'Chord per bar: chorus and build end with a cadence (E) and resolve into the verse','Dolgu: trampet 16’lık koşu, davul son iki vuruş; zil ile geçiş':'Fill: snare 16th-note run, kick on the last two hits; crash into the transition','Davul 1-2-3-4 (grup başları)':'Kick on 1-2-3-4 (group heads)','Trampet 2 ve 4 (backbeat), el çırpma üstüne katman':'Snare on 2 and 4 (backbeat), clap layered on top','Hi-hat aralarda (ofbit nefesi)':'Hi-hat in between (offbeat breath)','Bas davulla aynı yerde (kilit)':'Bass locked with the kick','Akustik gitar ikinci ibrede, ¾ hızda kayıyor':'Acoustic guitar on the second needle, drifting at ¾ speed','Saz ilk yarıda sorar, Ney ikinci yarıda cevap verir (soru-cevap)':'Saz asks in the first half, Ney answers in the second (call and response)','Saz solo yeri: 4. bölümde parlar':'Saz solo slot: shines in section 4','Plan: giriş, kıta, nakarat, solo, kıta, köprü, yükseliş, düşüş':'Plan: intro, verse, chorus, solo, verse, bridge, build, drop',
'Hicaz makamı, 112 BPM: Doğu ile Batı aynı sahnede':'Hicaz makam, 112 BPM: East and West on the same stage','Akor ölçü başına: kıta ve düşüşte Durak–Güçlü (makam ×1,1); nakarat ve yükseliş kadansla (E) bitip soloya ve düşüşe çözülür':'Chord per bar: Tonic–Dominant in verse and drop (makam ×1.1); chorus and build end with a cadence (E) and resolve into the solo and the drop','Kadans + dolgu aynı anda: bölüm geçişi ×1,5':'Cadence + fill together: section transition ×1.5','Dolgu: trampet 16’lık koşu, darbuka cevap, davul son vuruş (aksan); zil ile geçiş, düşmanlar kısa süre sersemler':'Fill: snare 16th-note run, darbuka answer, kick on the last hit (accent); crash into the transition, enemies are briefly stunned','Davul düm–tek: 1, 2-ve, 3, 4 · trampet 2 ve 4':'Kick düm–tek: 1, 2-and, 3, 4 · snare on 2 and 4','Hi-hat sekizlik; darbuka tek-ka süslemeleri':'Hi-hat eighths; darbuka tek-ka ornaments','Bas davulu izler, akorun köküne basar':'Bass follows the kick and lands on the chord root','Keman ikinci ibrede ¾ hızda, uzun sesler':'Violin on the second needle at ¾ speed, long tones','Düet (Sualli-cevaplı): gitar 4 adım sorar, ney 4 adım cevaplar; ikisi de ×1,2':'Duet (Call and response): guitar asks for 4 steps, ney answers for 4; both at ×1.2','Gitar: slide ile giriş, bend, vibrato; 3. cümlede tiz E′ üzerinde 4 adım feedback → Doruk patlaması':'Guitar: slide-in, bend, vibrato; in phrase 3 four steps of feedback on high E′ → Peak burst','Ney: dairesel nefesle uzun nota, tepede D′ 4 adım vibrato → Doruk; growl hırıltısı':'Ney: long notes with circular breathing, 4 steps of vibrato on high D′ → Peak; growl rasp','Seyir: ikisi de kökte (A′) uzun notayla bitirir → Karar ×1,25 · Doruk ×1,2 · cümle arası nefes → Soru–cevap ×1,15':'Seyir: both end on a long root note (A′) → Cadence ×1.25 · Peak ×1.2 · a breath between phrases → Call–response ×1.15','Plan: giriş, kıta, nakarat, solo, köprü, yükseliş, düşüş, solo':'Plan: intro, verse, chorus, solo, bridge, build, drop, solo'
};
let EN_RE=null,EN_CACHE=new Map();
function T(s){if(!S||S.lang!=='en'||!s||typeof s!=='string')return s;const c=EN_CACHE.get(s);if(c!==undefined)return c;const t=s.trim();let out;if(EN[t]!==undefined)out=s.replace(t,EN[t]);else{if(!EN_RE)EN_RE=Object.keys(EN).filter(k=>k.length>=3).sort((a,b)=>b.length-a.length).map(k=>[k,new RegExp('(?<![\\p{L}])'+k.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'(?![\\p{L}])','gu'),EN[k]]);out=s;for(const [k,re,v] of EN_RE){if(out.includes(k))out=out.replace(re,v)}}EN_CACHE.set(s,out);return out}
function i18n(root){if(!S||S.lang!=='en'||!root)return;const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);
 nodes.forEach(n=>{const p=n.parentNode;if(!p||p.tagName==='SCRIPT'||p.tagName==='STYLE'||p.tagName==='TEXTAREA')return;const v=n.nodeValue;if(!v||!/[A-Za-zÇĞİÖŞÜçğıöşü]/.test(v))return;const t=T(v);if(t!==v)n.nodeValue=t});
 root.querySelectorAll('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(a=>{const v=el.getAttribute(a);if(v){const t=T(v);if(t!==v)el.setAttribute(a,t)}}))}
